_wandb:
    value:
        cli_version: 0.27.0
        e:
            1ugdmlrky928o4fmzxjoaw7xkvrpim6p:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "156157632512"
                        used: "106446503936"
                email: ramachandranaadarsh@gmail.com
                executable: /home/aadarsh-ram/Projects/da6401_assignment_3/.venv/bin/python
                git:
                    commit: 2a3f0b6c6e110710277949057e75acb8f92a409a
                    remote: git@github.com:aadarshram/da6401_assignment_3.git
                gpu: NVIDIA GeForce MX570 A
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce MX570 A
                      uuid: GPU-1bcc6f59-1501-0290-d90d-9f4063ebc4bd
                host: aadarsh-ram-Vostro-5620
                memory:
                    total: "16436477952"
                os: Linux-6.17.0-23-generic-x86_64-with-glibc2.39
                program: /home/aadarsh-ram/Projects/da6401_assignment_3/train.py
                python: CPython 3.13.5
                root: /home/aadarsh-ram/Projects/da6401_assignment_3
                startedAt: "2026-05-18T18:36:01.732568Z"
                writerId: 1ugdmlrky928o4fmzxjoaw7xkvrpim6p
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 33
                - 49
                - 51
            "2":
                - 1
                - 33
                - 49
                - 51
            "3":
                - 16
            "4": 3.13.5
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
"N":
    value: 1
batch_size:
    value: 1
d_ff:
    value: 256
d_model:
    value: 128
dropout:
    value: 0.1
learning_rate:
    value: 0.9
num_epochs:
    value: 1
num_heads:
    value: 1
quick_test:
    value: false
src_vocab_size:
    value: 18669
tgt_vocab_size:
    value: 9797
